language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
sudo: false
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
script: "./bin/travis_script.sh"
