language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
sudo: false
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-354036443
script: "./bin/travis_script.sh"
