version: 1.0.{build}

environment:

  matrix:
    - RUBY_VERSION: "22-x64"
      PLATFORM: "x64"
    - RUBY_VERSION: "22"
      PLATFORM: "Win32"

install:
  - SET PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - SET DEVKIT=C:\Ruby%RUBY_VERSION%\DevKit
  - "%DEVKIT%\\devkitvars.bat"
  - gem update --system
  - gem install bundler --no-rdoc --no-ri
  - bundler env
  - bundle install

test_script:
  - bundle exec rspec
